version: "3"
services: 
    rabbit:
        container_name: rabbit
        image: rabbitmq
        ports: 
            - 5672:5672
        network_mode: bridge
    user:
        container_name: user-services
        restart: always
        build: ./micro-services/user-service
        ports: 
            - 4000:4000
        depends_on: 
            - rabbit
        links: 
            - rabbit
        network_mode: bridge

